"""empty message

Revision ID: 401ef2de2968
Revises: 5a2d1050a4d9
Create Date: 2018-11-01 16:38:56.047316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401ef2de2968'
down_revision = '5a2d1050a4d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('flag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novels', 'flag')
    # ### end Alembic commands ###
