"""empty message

Revision ID: 5a2d1050a4d9
Revises: e3729b5abc40
Create Date: 2018-10-30 22:24:20.539586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2d1050a4d9'
down_revision = 'e3729b5abc40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('fonts', sa.Integer(), nullable=True))
    op.add_column('novels', sa.Column('status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novels', 'status')
    op.drop_column('novels', 'fonts')
    # ### end Alembic commands ###
