""" 模型

Revision ID: e3729b5abc40
Revises: 
Create Date: 2018-10-27 13:13:38.276381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3729b5abc40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('image', sa.Binary(), nullable=True),
    sa.Column('last_update', sa.String(length=64), nullable=True),
    sa.Column('about_book', sa.Text(), nullable=True),
    sa.Column('book_url', sa.String(length=128), nullable=True),
    sa.Column('search_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novels_author'), 'novels', ['author'], unique=False)
    op.create_index(op.f('ix_novels_book_name'), 'novels', ['book_name'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_name', sa.String(length=128), nullable=True),
    sa.Column('chapter_url', sa.String(length=128), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_chapter_number'), 'chapters', ['chapter_number'], unique=False)
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contents')
    op.drop_index(op.f('ix_chapters_chapter_number'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_book_name'), table_name='novels')
    op.drop_index(op.f('ix_novels_author'), table_name='novels')
    op.drop_table('novels')
    # ### end Alembic commands ###
